/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raju
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel = new javax.swing.JPanel();
        male_image = new javax.swing.JLabel();
        female_image = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_student = new javax.swing.JButton();
        student_operations = new javax.swing.JButton();
        show_student = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        add_admin = new javax.swing.JButton();
        admin_operation = new javax.swing.JButton();
        show_admin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        home_item = new javax.swing.JMenuItem();
        logout_item = new javax.swing.JMenuItem();
        about_menu = new javax.swing.JMenu();
        about_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        home_panel.setBackground(new java.awt.Color(0, 0, 27));
        home_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Home", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Kristen ITC", 1, 24), new java.awt.Color(0, 153, 153))); // NOI18N
        home_panel.setForeground(new java.awt.Color(0, 0, 27));

        male_image.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\iconfinder_130-man-student-2_3099383.png")); // NOI18N

        female_image.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\iconfinder_132-woman-student-2_3099385.png")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Student");

        jLabel2.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Registration");

        jLabel3.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("System");

        add_student.setBackground(new java.awt.Color(51, 0, 51));
        add_student.setForeground(new java.awt.Color(0, 0, 255));
        add_student.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\iconfinder_Student-3_379383.png")); // NOI18N
        add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_studentActionPerformed(evt);
            }
        });

        student_operations.setBackground(new java.awt.Color(51, 0, 51));
        student_operations.setForeground(new java.awt.Color(0, 0, 255));
        student_operations.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\iconfinder_setting_icon_2541669.png")); // NOI18N
        student_operations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_operationsActionPerformed(evt);
            }
        });

        show_student.setBackground(new java.awt.Color(51, 0, 51));
        show_student.setForeground(new java.awt.Color(0, 0, 255));
        show_student.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\teamwork.png")); // NOI18N
        show_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_studentActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Add Student");

        jLabel5.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Operation's");

        jLabel6.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 0));
        jLabel6.setText("Show Student's");

        add_admin.setBackground(new java.awt.Color(51, 0, 51));
        add_admin.setForeground(new java.awt.Color(0, 0, 255));
        add_admin.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\iconfinder_Boy_child_school_boy_student_2992468.png")); // NOI18N
        add_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_adminActionPerformed(evt);
            }
        });

        admin_operation.setBackground(new java.awt.Color(51, 0, 51));
        admin_operation.setForeground(new java.awt.Color(0, 0, 255));
        admin_operation.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\gear.png")); // NOI18N
        admin_operation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_operationActionPerformed(evt);
            }
        });

        show_admin.setBackground(new java.awt.Color(51, 0, 51));
        show_admin.setForeground(new java.awt.Color(0, 0, 255));
        show_admin.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\collaboration.png")); // NOI18N
        show_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_adminActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Add Admin");

        jLabel8.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("Operation's");

        jLabel9.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("Show Admin's");

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_panelLayout.createSequentialGroup()
                        .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(home_panelLayout.createSequentialGroup()
                                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(add_admin))
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel7))
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(male_image)))
                                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, home_panelLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(jLabel8)
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel9))
                                            .addGroup(home_panelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(home_panelLayout.createSequentialGroup()
                                                        .addComponent(jLabel5)
                                                        .addGap(240, 240, 240))
                                                    .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(show_admin)))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(home_panelLayout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel1))
                                            .addGroup(home_panelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(female_image)
                                        .addGap(123, 123, 123))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, home_panelLayout.createSequentialGroup()
                                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel4))
                                    .addGroup(home_panelLayout.createSequentialGroup()
                                        .addComponent(add_student)
                                        .addGap(56, 56, 56)
                                        .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(admin_operation)
                                            .addGroup(home_panelLayout.createSequentialGroup()
                                                .addComponent(student_operations)
                                                .addGap(45, 45, 45)
                                                .addComponent(show_student))
                                            .addComponent(jLabel3))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(48, 48, 48))
                    .addGroup(home_panelLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(home_panelLayout.createSequentialGroup()
                        .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(female_image, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(home_panelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(male_image))
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)))
                .addGap(27, 27, 27)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(student_operations)
                    .addComponent(show_student)
                    .addComponent(add_student))
                .addGap(18, 18, 18)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(admin_operation)
                    .addComponent(add_admin)
                    .addComponent(show_admin))
                .addGap(18, 18, 18)
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 0));
        jMenuBar1.setForeground(new java.awt.Color(51, 153, 0));

        file_menu.setBackground(new java.awt.Color(51, 153, 0));
        file_menu.setText("File");

        home_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        home_item.setBackground(new java.awt.Color(51, 153, 0));
        home_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        home_item.setForeground(new java.awt.Color(0, 0, 102));
        home_item.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\icons8-exterior-30.png")); // NOI18N
        home_item.setText("Home");
        home_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_itemActionPerformed(evt);
            }
        });
        file_menu.add(home_item);

        logout_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        logout_item.setBackground(new java.awt.Color(51, 153, 0));
        logout_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        logout_item.setForeground(new java.awt.Color(0, 0, 102));
        logout_item.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\icons8-sign-out-30.png")); // NOI18N
        logout_item.setText("Logout");
        logout_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_itemActionPerformed(evt);
            }
        });
        file_menu.add(logout_item);

        jMenuBar1.add(file_menu);

        about_menu.setBackground(new java.awt.Color(51, 153, 0));
        about_menu.setText("About");

        about_item.setBackground(new java.awt.Color(51, 153, 0));
        about_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        about_item.setForeground(new java.awt.Color(0, 0, 102));
        about_item.setIcon(new javax.swing.ImageIcon("G:\\Java Programming Code\\DATABASE PROJECT\\Student Registration System\\Images\\icons8-female-profile-30.png")); // NOI18N
        about_item.setText("About");
        about_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_itemActionPerformed(evt);
            }
        });
        about_menu.add(about_item);

        jMenuBar1.add(about_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(682, 724));
    }// </editor-fold>//GEN-END:initComponents

    private void home_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_itemActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home obj = new home();
        obj.setVisible(true);
    }//GEN-LAST:event_home_itemActionPerformed

    private void about_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_itemActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        about obj = new about();
        obj.setVisible(true);
    }//GEN-LAST:event_about_itemActionPerformed

    private void student_operationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_operationsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        student obj = new student();
        obj.setVisible(true);

    }//GEN-LAST:event_student_operationsActionPerformed

    private void add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_studentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        addStudent obj = new addStudent();
        obj.setVisible(true);
    }//GEN-LAST:event_add_studentActionPerformed

    private void show_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_studentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        showStudent obj = new showStudent();
        obj.setVisible(true);

    }//GEN-LAST:event_show_studentActionPerformed

    private void admin_operationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_operationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        admin obj = new admin();
        obj.setVisible(true);
    }//GEN-LAST:event_admin_operationActionPerformed

    private void show_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_adminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        showAdmin obj = new showAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_show_adminActionPerformed

    private void add_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_adminActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        addAdmin obj = new addAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_add_adminActionPerformed

    private void logout_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_itemActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login obj = new login();
        obj.setVisible(true);
    }//GEN-LAST:event_logout_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about_item;
    private javax.swing.JMenu about_menu;
    private javax.swing.JButton add_admin;
    private javax.swing.JButton add_student;
    private javax.swing.JButton admin_operation;
    private javax.swing.JLabel female_image;
    private javax.swing.JMenu file_menu;
    private javax.swing.JMenuItem home_item;
    private javax.swing.JPanel home_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem logout_item;
    private javax.swing.JLabel male_image;
    private javax.swing.JButton show_admin;
    private javax.swing.JButton show_student;
    private javax.swing.JButton student_operations;
    // End of variables declaration//GEN-END:variables
}
